spring:
  jpa:
    show-sql: false

zovik:
  runner:
    docker-host: npipe:////./pipe/docker_engine
    workspace-dir: ${java.io.tmpdir}/zovik/workspaces
  git:
    clone-dir: ${java.io.tmpdir}/zovik/repos
  artifacts:
    storage-dir: ${java.io.tmpdir}/zovik/artifacts
